### PR TITLE
Store data to db on employee save

### PR DESCRIPTION
**Pull request by Programm3r**
> we are supposed to store data to db #3

ef code first implementation that stores the employee data to db #hacktoberfest

### CODE REVIEW

**Comment by kiranshahi** [comment]
@Programm3r can you help to document on how to work with database 👍

**Comment by Programm3r** [comment]
@kiranshahi are ysou referring to documenting the code or `.md` file?

**Comment by kiranshahi** [comment]
any I didn't get idea how to work with ef code first approach

**Comment by Programm3r** [comment]
I'll see what I can do - a bit busy at work, but as soon as I get some time

**Comment by kiranshahi** [comment]
Ok sure :)

**Comment by kiranshahi** [comment]
Ok, thank you :)

**Pull request merged**
